"""empty message

Revision ID: 1c9845988bb1
Revises: 52ca2140e4b
Create Date: 2015-04-26 16:17:16.017000

"""

# revision identifiers, used by Alembic.
revision = '1c9845988bb1'
down_revision = '52ca2140e4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Visit', sa.Column('payment_notes', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Visit', 'payment_notes')
    ### end Alembic commands ###
