"""empty message

Revision ID: 1f42d7e34620
Revises: 3ed8cbe01d63
Create Date: 2015-04-25 22:56:47.599978

"""

# revision identifiers, used by Alembic.
revision = '1f42d7e34620'
down_revision = '3ed8cbe01d63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescribed_test', sa.Text(), nullable=True),
    sa.Column('test_notes', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['Visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Status_Log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['Visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('status_log')
    op.drop_table('Test_Patient')
    op.drop_column('Patient', 'period_last_date')
    op.add_column('Prescription', sa.Column('dentist_prescription', sa.Text(), nullable=True))
    op.add_column('Prescription', sa.Column('doctor_prescription', sa.Text(), nullable=True))
    op.add_column('Prescription', sa.Column('notes_pharmacy', sa.Text(), nullable=True))
    op.add_column('Prescription', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('Prescription', sa.Column('visit_id', sa.Integer(), nullable=True))
    op.drop_column('Prescription', 'notes_prescription')
    op.add_column('Visit', sa.Column('bp_diastolic', sa.SmallInteger(), nullable=True))
    op.add_column('Visit', sa.Column('bp_systolic', sa.SmallInteger(), nullable=True))
    op.add_column('Visit', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('Visit', sa.Column('payment_other_amount', sa.Float(), nullable=True))
    op.add_column('Visit', sa.Column('period_last_date', sa.Date(), nullable=True))
    op.add_column('Visit', sa.Column('weight', sa.Float(), nullable=True))
    op.drop_column('Visit', 'lab_test_2_notes_doctor')
    op.drop_column('Visit', 'lab_test_1_doctor')
    op.drop_column('Visit', 'prescription_4_doctor')
    op.drop_column('Visit', 'bp_doc_systolic')
    op.drop_column('Visit', 'lab_test_1_notes_doctor')
    op.drop_column('Visit', 'prescription_1_dentist')
    op.drop_column('Visit', 'prescription_4_dentist')
    op.drop_column('Visit', 'prescription_2_dentist')
    op.drop_column('Visit', 'prescription_2_doctor')
    op.drop_column('Visit', 'prescription_3_dentist')
    op.drop_column('Visit', 'bp_dentist_diastolic')
    op.drop_column('Visit', 'weight_dentist')
    op.drop_column('Visit', 'bp_dentist_systolic')
    op.drop_column('Visit', 'lab_test_2_notes_dentist')
    op.drop_column('Visit', 'prescription_1_notes_doctor')
    op.drop_column('Visit', 'payment_amount')
    op.drop_column('Visit', 'lab_test_3_notes_doctor')
    op.drop_column('Visit', 'lab_test_4_doctor')
    op.drop_column('Visit', 'lab_test_4_notes_doctor')
    op.drop_column('Visit', 'lab_test_1_dentist')
    op.drop_column('Visit', 'prescription_3_notes_dentist')
    op.drop_column('Visit', 'lab_test_4_notes_dentist')
    op.drop_column('Visit', 'prescription_3_doctor')
    op.drop_column('Visit', 'prescription_1_doctor')
    op.drop_column('Visit', 'lab_test_3_dentist')
    op.drop_column('Visit', 'weight_doctor')
    op.drop_column('Visit', 'lab_test_3_notes_dentist')
    op.drop_column('Visit', 'lab_test_2_dentist')
    op.drop_column('Visit', 'prescription_2_notes_doctor')
    op.drop_column('Visit', 'prescription_2_notes_dentist')
    op.drop_column('Visit', 'lab_test_2_doctor')
    op.drop_column('Visit', 'prescription_4_notes_dentist')
    op.drop_column('Visit', 'lab_test_3_doctor')
    op.drop_column('Visit', 'prescription_1_notes_dentist')
    op.drop_column('Visit', 'lab_test_1_notes_dentist')
    op.drop_column('Visit', 'prescription_3_notes_doctor')
    op.drop_column('Visit', 'bp_doc_diastolic')
    op.drop_column('Visit', 'prescription_4_notes_doctor')
    op.drop_column('Visit', 'lab_test_4_dentist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Visit', sa.Column('lab_test_4_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_4_notes_doctor', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('bp_doc_diastolic', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('Visit', sa.Column('prescription_3_notes_doctor', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_1_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('prescription_1_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_3_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_4_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_2_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_2_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('prescription_2_notes_doctor', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_2_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_3_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('weight_doctor', mysql.FLOAT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_3_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_1_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_3_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_4_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('prescription_3_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_1_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_4_notes_doctor', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_4_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_3_notes_doctor', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('payment_amount', mysql.FLOAT(), nullable=True))
    op.add_column('Visit', sa.Column('prescription_1_notes_doctor', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_2_notes_dentist', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('bp_dentist_systolic', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('Visit', sa.Column('weight_dentist', mysql.FLOAT(), nullable=True))
    op.add_column('Visit', sa.Column('bp_dentist_diastolic', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('Visit', sa.Column('prescription_3_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_2_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_2_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_4_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('prescription_1_dentist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_1_notes_doctor', mysql.TEXT(), nullable=True))
    op.add_column('Visit', sa.Column('bp_doc_systolic', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('Visit', sa.Column('prescription_4_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_1_doctor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Visit', sa.Column('lab_test_2_notes_doctor', mysql.TEXT(), nullable=True))
    op.drop_column('Visit', 'weight')
    op.drop_column('Visit', 'period_last_date')
    op.drop_column('Visit', 'payment_other_amount')
    op.drop_column('Visit', 'patient_id')
    op.drop_column('Visit', 'bp_systolic')
    op.drop_column('Visit', 'bp_diastolic')
    op.add_column('Prescription', sa.Column('notes_prescription', mysql.TEXT(), nullable=True))
    op.drop_column('Prescription', 'visit_id')
    op.drop_column('Prescription', 'patient_id')
    op.drop_column('Prescription', 'notes_pharmacy')
    op.drop_column('Prescription', 'doctor_prescription')
    op.drop_column('Prescription', 'dentist_prescription')
    op.add_column('Patient', sa.Column('period_last_date', sa.DATE(), nullable=True))
    op.create_table('Test_Patient',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('status_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('visit_id', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('Status_Log')
    op.drop_table('Lab')
    ### end Alembic commands ###
