"""empty message

Revision ID: 23d2d0d54f91
Revises: None
Create Date: 2015-04-25 15:03:43.363249

"""

# revision identifiers, used by Alembic.
revision = '23d2d0d54f91'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test_Patient', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('Test_Patient', sa.Column('children_count', sa.SmallInteger(), nullable=True))
    op.add_column('Test_Patient', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('Test_Patient', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('Test_Patient', sa.Column('references', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Test_Patient', 'references')
    op.drop_column('Test_Patient', 'phone')
    op.drop_column('Test_Patient', 'occupation')
    op.drop_column('Test_Patient', 'children_count')
    op.drop_column('Test_Patient', 'address')
    ### end Alembic commands ###
