"""empty message

Revision ID: 268857fdc329
Revises: None
Create Date: 2015-04-26 00:19:26.804519

"""

# revision identifiers, used by Alembic.
revision = '268857fdc329'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
