"""empty message

Revision ID: 2cb06eccea6c
Revises: 23d2d0d54f91
Create Date: 2015-04-25 15:12:38.731002

"""

# revision identifiers, used by Alembic.
revision = '2cb06eccea6c'
down_revision = '23d2d0d54f91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
