"""empty message

Revision ID: 397a40885279
Revises: 268857fdc329
Create Date: 2015-04-26 14:38:33.665000

"""

# revision identifiers, used by Alembic.
revision = '397a40885279'
down_revision = '268857fdc329'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Visit', sa.Column('visit_date', sa.Date(), nullable=True))
    op.create_table('StatusLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['Visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Status_Log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Visit', 'visit_date')
    op.create_table('Status_Log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['Visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('StatusLog')
    ### end Alembic commands ###
