"""empty message

Revision ID: 3ed8cbe01d63
Revises: 2cb06eccea6c
Create Date: 2015-04-25 22:07:35.698512

"""

# revision identifiers, used by Alembic.
revision = '3ed8cbe01d63'
down_revision = '2cb06eccea6c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Test_Patient', 'occupation')
    op.drop_column('Test_Patient', 'phone')
    op.drop_column('Test_Patient', 'children_count')
    op.drop_column('Test_Patient', 'references')
    op.drop_column('Test_Patient', 'address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test_Patient', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Test_Patient', sa.Column('references', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Test_Patient', sa.Column('children_count', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('Test_Patient', sa.Column('phone', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Test_Patient', sa.Column('occupation', mysql.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
