"""empty message

Revision ID: 4b8c38ea2b8d
Revises: None
Create Date: 2014-08-15 22:08:28.558188

"""

# revision identifiers, used by Alembic.
revision = '4b8c38ea2b8d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
