"""empty message

Revision ID: 5013277cf9b1
Revises: None
Create Date: 2014-10-04 13:04:42.362967

"""

# revision identifiers, used by Alembic.
revision = '5013277cf9b1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
