"""empty message

Revision ID: 52ca2140e4b
Revises: 397a40885279
Create Date: 2015-04-26 15:36:41.631000

"""

# revision identifiers, used by Alembic.
revision = '52ca2140e4b'
down_revision = '397a40885279'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StatusLog', sa.Column('statusLog_visit_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'StatusLog_ibfk_1', 'StatusLog', type_='foreignkey')
    op.create_foreign_key(None, 'StatusLog', 'Visit', ['statusLog_visit_id'], ['id'])
    op.drop_column('StatusLog', 'visit_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StatusLog', sa.Column('visit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'StatusLog', type_='foreignkey')
    op.create_foreign_key(u'StatusLog_ibfk_1', 'StatusLog', 'Visit', ['visit_id'], ['id'])
    op.drop_column('StatusLog', 'statusLog_visit_id')
    ### end Alembic commands ###
