"""initial migration

Revision ID: 9911614c892
Revises: None
Create Date: 2014-06-02 23:20:50.924759

"""

# revision identifiers, used by Alembic.
revision = '9911614c892'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwdhash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'pwdhash')
    ### end Alembic commands ###
