"""empty message

Revision ID: b4fa1317cd7
Revises: None
Create Date: 2014-08-15 20:22:03.514058

"""

# revision identifiers, used by Alembic.
revision = 'b4fa1317cd7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('pwhash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('patient_number', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('bp_systolic', sa.SmallInteger(), nullable=True),
    sa.Column('bp_diastolic', sa.SmallInteger(), nullable=True),
    sa.Column('pulse', sa.SmallInteger(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('respirations', sa.Float(), nullable=True),
    sa.Column('complaint', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('exam', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment1', sa.String(length=255), nullable=True),
    sa.Column('treatment2', sa.String(length=255), nullable=True),
    sa.Column('treatment3', sa.String(length=255), nullable=True),
    sa.Column('treatment4', sa.String(length=255), nullable=True),
    sa.Column('treatment5', sa.String(length=255), nullable=True),
    sa.Column('treatment6', sa.String(length=255), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('exam_notes', sa.Text(), nullable=True),
    sa.Column('prescription_given', sa.Boolean(), nullable=True),
    sa.Column('prescription_description', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('status_change_timestamp', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_given', sa.String(length=255), nullable=True),
    sa.Column('amount_given', sa.String(length=255), nullable=True),
    sa.Column('pharmacy_notes', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.SmallInteger(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('payment_other', sa.String(length=255), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('roles')
    op.drop_table('users')
    op.add_column(u'patient', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column(u'patient', sa.Column('alcohol', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column(u'patient', sa.Column('asthma', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column(u'patient', sa.Column('children_count', sa.SmallInteger(), nullable=True))
    op.add_column(u'patient', sa.Column('coffee', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('diabetes', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('drugs', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('drugs_notes', sa.String(length=255), nullable=True))
    op.add_column(u'patient', sa.Column('epilepsy', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('family_history', sa.Text(), nullable=True))
    op.add_column(u'patient', sa.Column('gender', sa.SmallInteger(), nullable=True))
    op.add_column(u'patient', sa.Column('guardian', sa.String(length=255), nullable=True))
    op.add_column(u'patient', sa.Column('ht', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('immunizations', sa.Text(), nullable=True))
    op.add_column(u'patient', sa.Column('mother_name', sa.String(length=255), nullable=True))
    op.add_column(u'patient', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column(u'patient', sa.Column('patient_notes', sa.Text(), nullable=True))
    op.add_column(u'patient', sa.Column('period_age_start', sa.SmallInteger(), nullable=True))
    op.add_column(u'patient', sa.Column('period_last_date', sa.Date(), nullable=True))
    op.add_column(u'patient', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column(u'patient', sa.Column('relation', sa.String(length=255), nullable=True))
    op.add_column(u'patient', sa.Column('sickle_cell', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('surgeries', sa.Text(), nullable=True))
    op.add_column(u'patient', sa.Column('tb', sa.Boolean(), nullable=True))
    op.add_column(u'patient', sa.Column('tea', sa.Boolean(), nullable=True))
    op.drop_column(u'patient', 'sex')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'patient', sa.Column('sex', sa.SMALLINT(), nullable=True))
    op.drop_column(u'patient', 'tea')
    op.drop_column(u'patient', 'tb')
    op.drop_column(u'patient', 'surgeries')
    op.drop_column(u'patient', 'sickle_cell')
    op.drop_column(u'patient', 'relation')
    op.drop_column(u'patient', 'phone')
    op.drop_column(u'patient', 'period_last_date')
    op.drop_column(u'patient', 'period_age_start')
    op.drop_column(u'patient', 'patient_notes')
    op.drop_column(u'patient', 'occupation')
    op.drop_column(u'patient', 'mother_name')
    op.drop_column(u'patient', 'immunizations')
    op.drop_column(u'patient', 'ht')
    op.drop_column(u'patient', 'guardian')
    op.drop_column(u'patient', 'gender')
    op.drop_column(u'patient', 'family_history')
    op.drop_column(u'patient', 'epilepsy')
    op.drop_column(u'patient', 'drugs_notes')
    op.drop_column(u'patient', 'drugs')
    op.drop_column(u'patient', 'diabetes')
    op.drop_column(u'patient', 'coffee')
    op.drop_column(u'patient', 'children_count')
    op.drop_column(u'patient', 'birth_date')
    op.drop_column(u'patient', 'asthma')
    op.drop_column(u'patient', 'allergies')
    op.drop_column(u'patient', 'alcohol')
    op.drop_column(u'patient', 'address')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=True),
    sa.Column('pwhash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('pwdhash', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payment')
    op.drop_table('pharmacy')
    op.drop_table('status')
    op.drop_table('visit')
    op.drop_table('user')
    ### end Alembic commands ###
